### ISSUE TITLE
Guacamole containers not started

### ISSUE THREAD

**Issue by ipilcher** [RHFieldProductManagement/openshift-aio#13]
Deploying for the OCP 4.9 hackfest & ran into an issue where the Postgres password couldn't be set, because the container wasn't running.  Had to change the `state` of the containers in `deploy_guac.yml` to `started`, rather than just `present` to make things work.

See the `ocp49_hackfest` branch.

**Comment by hgeaydem** [comment]
this is fixed in the roles-enabled aio that is now main branch
