### ISSUE TITLE
Use Rocky, rather than CentOS, for bastion VM

### ISSUE THREAD

**Issue by ipilcher** [RHFieldProductManagement/openshift-aio#23]
Probably want to move away from using CentOS 8, as it's EOL & doesn't get updates anymore.  At some point, EPEL & other repos will probably hit dependency issues.

**Comment by hgeaydem** [comment]
it's actually now using Centos Streams as plain old Centos already was experiencing that kind of issues indeed. I've added Rocky Linux support for the hypervisor since that's now required for equinix tho

**Comment by ipilcher** [comment]
Ah.  Gotcha.  Didn't pick up on that.  (Was just going by the Ansible task name.)
