### ISSUE TITLE
Firewalld 100% compatibility

### ISSUE THREAD

**Issue by pnavarro** [RHFieldProductManagement/openshift-aio#24]
In a RHEL 8.4 with firewalld installed I'm getting the following errors:

Ansible 2.9 
TASK [base_virt : Enable port 9001 forwarding to bastion:9001 with firewalld] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [10.19.115.66]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (firewalld) module: port_forward Supported parameters include: icmp_block, icmp_block_inversion, immediate, interface, masquerade, offline, permanent, port, rich_rule, service, source, state, timeout, zone"}

Ansible 2.11

TASK [base_virt : Enable port 9001 forwarding to bastion:9001 with firewalld] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [10.19.115.66]: FAILED! => {"changed": false, "msg": "argument 'port_forward' is of type <class 'dict'> and we were unable to convert to list: <class 'dict'> cannot be converted to a list"}

**Comment by hgeaydem** [comment]
As Ansible doesn't provide an easy way to support multiple firewalls and a network overhaul will soon take place, closing this and made some updates in the code to make sure firewalld gets disabled/iptables is being used instead
