### ISSUE TITLE
Trouble deploying cluster with 2 worker nodes.

### ISSUE THREAD

**Issue by cowlesav** [RHFieldProductManagement/openshift-aio#41]
Tried a simple deployment with mostly default values. When I do I receive the following failure: 

TASK [deploy_bastion : Remove worker3 from install-config if ocp4_aio_ocp_workers is 2] ***************************************************************************************************************
fatal: [192.168.123.100]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}

If I change the number of workers to 3, the deployment continues without an issue. 

It looks like the failure is affected by the following play in:

openshift-aio/playbooks/roles/deploy_bastion/tasks/deploy_bastion_ipi.yml

_- name: Remove workers from install-config if compact
  ansible.builtin.command:
    cmd: sed -i '/{{ item }}/,+8d' /root/lab/install-config.yaml
    warn: false
  loop:
    - "worker1"
    - "worker2"
    - "worker3"
  when: ocp4_aio_deploy_compact or hostvars['localhost']['override_deploy_compact']

- name: Remove worker3 from install-config if ocp4_aio_ocp_workers is 2
  ansible.builtin.command:
    cmd: sed -i '/worker3/,+8d' /root/lab/install-config.yaml
    warn: false
  when:
    - not ocp4_aio_deploy_ocs
    - not ocp4_aio_deploy_compact
    - ocp4_aio_ocp_workers == 2

- name: Remove worker2 from install-config if ocp4_aio_ocp_workers is 1
  ansible.builtin.command:
    cmd: sed -i '/{{ item }}/,+8d' /root/lab/install-config.yaml
    warn: false
  loop:
    - "worker2"
    - "worker3"_

Commenting the warn command allows the deployment to proceed with 2 worker nodes successfully.

**Comment by hgeaydem** [comment]
Thanks for spotting it and providing a solution :)

Working on applying it now :)

**Comment by hgeaydem** [comment]
Fix applied, please update requirements ;)
